// Generates src/resources/libFiles/lpc/index.ts from the LPC language server's
// efun definition headers. These are the LPC equivalent of TypeScript's lib.d.ts
// files: they are fed to the compiler host as a virtual file system so that
// `#include`s inside the efun headers resolve in the browser.
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const efunsRoot = path.resolve(repoRoot, "node_modules/lpc/efuns");
const outDir = path.resolve(repoRoot, "src/resources/libFiles/lpc");

/** @returns {string[]} paths relative to `efunsRoot` */
function collect(dir) {
  const result = [];
  for (const entry of fs.readdirSync(path.join(efunsRoot, dir), { withFileTypes: true })) {
    const rel = path.posix.join(dir, entry.name);
    if (entry.isDirectory()) {
      result.push(...collect(rel));
    } else if (entry.name.endsWith(".h")) {
      result.push(rel);
    }
  }
  return result;
}

const files = ["fluffos", "ldmud"].flatMap((driver) => collect(driver));
files.sort();

const entries = files.map((rel) => {
  const text = fs.readFileSync(path.join(efunsRoot, rel), "utf8");
  return `  { fileName: "/efuns/${rel}", text: ${JSON.stringify(text)} },`;
}).join("\n");

const output = `// deno-fmt-ignore-file
/* Generated by scripts/copyLpcLibFiles.mjs from the lpc language server's efuns/ folder. Do not edit! */

export interface LpcLibFile {
  fileName: string;
  text: string;
}

export const libFiles: LpcLibFile[] = [
${entries}
];
`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, "index.ts"), output);
console.log(`wrote ${files.length} lpc lib files to ${path.relative(repoRoot, outDir)}/index.ts`);
